const Config = {
  spotifyAccessToken:
    'BQBFSlpSqb-0dXLQO_boyOE74HXx_GfdE0J9BLJnKc9eOkAmUwhDfI7Kmj1JhCe_4VVHcR28AdbNAjiaiyHSpAz5-pZAJJzPVOjBxwhz0Hjq9vFLeQQvx3SwxSDDWDTdpHaqhDkwtLiLxoo3gBVjPzFKFKiK4eaSW88W1Jp7jckB1A7fNnWorqBK2HxROnXBboanzrAz9w5DRoQXjpJdr1RXkopUBgtTez3eUFokEoUdxwi7ig'
};

export default Config;
